# Generated by Django 5.0.6 on 2024-05-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='contra',
            field=models.CharField(default=1234, max_length=25),
            preserve_default=False,
        ),
    ]
