# Generated by Django 5.0.6 on 2024-05-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_paciente_contra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='contra',
            field=models.CharField(max_length=10),
        ),
    ]
