# Generated by Django 5.0.6 on 2024-06-21 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_mensaje_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='medico',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo_usuario': 'medico'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes', to='myapp.usuario'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('medico', 'Medico'), ('paciente', 'Paciente')], default='paciente', max_length=10),
            preserve_default=False,
        ),
    ]
